{
    "intro": "<p>highlighting the <span id=\"total-shippers\"></span> companies that paid the commonwealth of pennsylvania $250 a pop for the privilege of shipping wine directly to customers -- because the state is terrible at it.</p>",
    "chart_intro_1": "<p>On the map and in the filters above is essentially raw data: Every company that can ship wine directly to customers in the state, as registered with the Pennsylvania Liquor Control Board.</p><p>It's a novel concept in the commonwealth. It's only been legal since August 2016. <a href=\"http://www.lcb.pa.gov/Legal/Documents/003492.pdf\" target=\"_blank\">The rules are a little weird</a>.</p><p>The way the PLCB <a href=\"http://www.lcbapps.lcb.state.pa.us/webapp/Retail/Direct_Shippers_list.asp\" target=\"_blank\">presents this data</a> is, shall we say, unhelpful. There's no way to sort it or make sense of it or, really, dig into it at all.</p>Hence <a target=\"_blank\" href=\"https://www.youtube.com/watch?v=E8G5gSP64D4\">Grape Aphid. Scraped PLCB data gets cleaned up and added to and made more accessible and here we are.</p>",
    "chart_intro_2": "<p>Beyond the raw data, all place by place and one by one, sometimes the broader set has useful things to say. One thing that becomes clear fairly quickly is these are not all little wineries representing themselves.</p><p>There are more than a few companies in this data that represent or own a number of wineries and can ship those products to you. Pennsylvania doesn't give us any way to to know which ones or what their inventory is. The state doesn't point us to their websites.</p><p>One example is <a href=\"http://dvwinepartners.com/\" target=\"_blank\">Distinguished Vinyards & Wine Partners</a> which represents a handful of wineries in Oregon, California and Australia. In the PLCB's data it shows up as Lion Nathan USA, an old corporate name, at an address in Oregon not far from wine country, an hour or so from Portland. And that's it.</p><p>Even with the data in hand, there's so much more to explore.</p>",
    "chart1_1": "As we begin to look inside the data, maybe it isn't a surprise that most of these businesses are based in California.",
    "chart1_2": "There is no close second.",
    "chart2": "The counties with the most show how concentrated they can be. The top counties are in California, then Oregon, then Washington, with New York also in the picture. Pennsylvania -- the state with the second-most direct-wine-shippers -- consistently shows up for the first time at or near the bottom of the top 15 counties.",
    "chart3": "Here's where things start to get a little more revealing. Some of the wine-shippers use the same addresses -- at times because it's an office park home to a few of them, or because the same business handles a number of different wineries.",
    "chart4": "Where that's visible even more is in the contact email addresses. Several are represented at least a dozen times."
}
